### ISSUE TITLE
Positioning moves are also G1

### ISSUE THREAD

**Issue by ghost** [andrewhodel/dxfToMillcrum#2]
Example:

; MOVING TO this.tool.zClearance
G1 F2000 Z5
; MOVING TO FIRST POINT IN toolPath
G1 F2000 X824.42223646 Y83.32819546

Should be G0? My laser firmware activates on G1 and extenquishes on G0 moves. (:

**Comment by andrewhodel** [comment]
This is a Millcrum issue, not a dxfToMillcrum issue.
I've updated Millcrum to fix this issue - https://github.com/andrewhodel/millcrum/commit/7024ce812a9a7d8ba493002c285ab573aadef1c8
